# Generated by Django 4.2.4 on 2023-08-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
